sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Q7ldEl8PxTPjNkhV7yYyTUbxPoAoz8Byr7bX0Z8+t97GsiPIKZAEK6Syup7kOJMu8dkwQlrGnGx7sifv52k7JIP+ADHmiW2DeaMnLHQsZ2ExNihtT9AbLLkngu+CoHvwdpCgjVhpQsz0b/t09Xg7RG9Xi20STWj3WvX9Iu7ur3opbq3Iz5DyUd7rLa63Zf+ruqt7dugr6q4DcQKpRu/bfbi1Rc5Ta97kR4tkxU830wRuI43n4lakQI+DRVBGIVzXyPFaPAe7MbDYyV7XcoXgrsdDppwLFaRgLOBNgK6CqujDv2vOuQxITNxNMWcGx9HujtqkdnlvyTq9AEp7b7woMzk8mRljgqXDNyY+4OAH/Ts7y6ajRSHYUVBShDlfsOduLKv0OJwQrhCr0EFveDn1z91vS0rT2W9qv7qNUqo6AKYH2vFsfjxjlY63JUfcB2F8TwZ7WnI5Jy5h1jUuvd8Pe/nZzgQh8CC75kCU7QUjoSu7Zzf3Yd1Xw5OZUD6LSjOiOWxVkfmQuLW8VgrwQaOzXwcHEeP/j44UUP8ZFXNvFq38CUF5nOME1vYuBZyuj4Mh6sRjMeUMdMT+AxKSBeHNrgmBFN3CNtdmabE19vO/vD2U+nfY/dWZFOV29U7Fd152ox6c6D6yqnT1ll86bVfeBmeRVWZPpBK7ZtoUM/dbTkI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Pierre-and-His-People--Tales-of-the-Far-North.-Complete_6179
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy